### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by nick250386** [kesla/node-snappy#142]
Below is the error when I am installing snappy on a windows machine:

$ npm install snappy
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> snappy@5.0.5 install D:\testNPM\node_modules\snappy
> node-gyp rebuild

D:\testNPM\node_modules\snappy>if not defined npm_config_node_gyp (node "<NPM HOME>\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: getaddrinfo EAI_AGAIN nodejs.org:443
gyp ERR! stack     at Object.exports._errnoException (util.js:1026:11)
gyp ERR! stack     at errnoException (dns.js:33:15)
gyp ERR! stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "<NPM HOME>\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\testNPM\node_modules\snappy
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
mc@1.0.0 D:\testNPM
`-- d@0.1.1  extraneous

npm WARN mc@1.0.0 No description
npm WARN mc@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "<NPM HOME>\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "snappy"
npm ERR! node v6.9.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! snappy@5.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snappy@5.0.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the snappy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs snappy
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls snappy
npm ERR! There is likely additional logging output above.

Can you please suggest what could be going wrong here that the installation of snappy  package is failing?

**Comment by nick250386** [comment]
Hey Team, 
Any inputs on this issue will help me in making some progress on this project.
Thanks & Regards
Nishant
