### ISSUE TITLE
make: *** [Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-sinksource.o] Error 127

### ISSUE THREAD

**Issue by rihannarickeminem** [kesla/node-snappy#158]
```
npm i
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

> snappy@5.0.5 install /home/z/projects/catch_cronposts/node_modules/snappy
> node-gyp rebuild

make: вход в каталог «/home/z/projects/catch_cronposts/node_modules/snappy/build»
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-sinksource.o
make: g++: Command not found
deps/snappy/snappy.target.mk:103: recipe for target 'Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-sinksource.o' failed
make: *** [Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-sinksource.o] Error 127
make: выход из каталога «/home/z/projects/catch_cronposts/node_modules/snappy/build»
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/z/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.15.0-23-generic
gyp ERR! command "/home/z/.nvm/versions/node/v10.5.0/bin/node" "/home/z/.nvm/versions/node/v10.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/z/projects/catch_cronposts/node_modules/snappy
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN catch_vlink@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snappy@5.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snappy@5.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/z/.npm/_logs/2018-06-23T06_06_42_406Z-debug.log

```
how to switch from snappy to leveldown? 
or how to fix this problem?

**Comment by kesla** [comment]
@rihannarickeminem you need to be able to compile c++ to install this module. You can prob find info for your setup on how to fix that. I can't help you any further.

**Comment by kesla** [comment]
Hey,

The latest version of snappy (6.1.0) shouldn't have this problem anymore since it downloads a compiled version of the library. Please reopen if you still have an issue!
