### ISSUE TITLE
6.3.1 release failed

### ISSUE THREAD

**Issue by achille-roussel** [kesla/node-snappy#180]
Hello!

First of all, thanks for the quick review on #179!

It looks like there was an attempt to release version 6.3.1 but the CI jobs failed (https://travis-ci.org/github/kesla/node-snappy/builds/661246284?utm_source=github_status&utm_medium=notification)
```
prebuild-ci info begin Prebuild-CI version 2.3.0
prebuild-ci info build node abi 79
prebuild info begin Prebuild version 8.2.1
prebuild info build Preparing to prebuild snappy@6.3.1 for node 79 on linux-x64 using node-gyp
/home/travis/build/kesla/node-snappy/node_modules/node-abi/index.js:48
  throw new Error('Could not detect target for abi ' + abi + ' and runtime ' + runtime)
  ^
Error: Could not detect target for abi 79 and runtime node
    at getTarget (/home/travis/build/kesla/node-snappy/node_modules/node-abi/index.js:48:9)
    at prebuild (/home/travis/build/kesla/node-snappy/node_modules/prebuild/prebuild.js:26:46)
    at /home/travis/build/kesla/node-snappy/node_modules/prebuild/bin.js:56:5
    at /home/travis/build/kesla/node-snappy/node_modules/async/dist/async.js:3110:16
    at replenish (/home/travis/build/kesla/node-snappy/node_modules/async/dist/async.js:1011:17)
    at /home/travis/build/kesla/node-snappy/node_modules/async/dist/async.js:1016:9
    at eachLimit$1 (/home/travis/build/kesla/node-snappy/node_modules/async/dist/async.js:3196:24)
    at Object.<anonymous> (/home/travis/build/kesla/node-snappy/node_modules/async/dist/async.js:1046:16)
    at Object.<anonymous> (/home/travis/build/kesla/node-snappy/node_modules/prebuild/bin.js:55:9)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
npm ERR! Test failed.  See above for more details.
```

Is there anything I can do to help?

**Comment by achille-roussel** [comment]
Any updates?

**Comment by achille-roussel** [comment]
Hello, do you have any updates to share on this issue?

**Comment by kesla** [comment]
Hey, sorry, I missed this somehow, v 6.3.3 is now released
