### ISSUE TITLE
v6.3.2: gyp build fails on node 13.13.0

### ISSUE THREAD

**Issue by oaleynik** [kesla/node-snappy#185]
```
❯ npm i snappy

> snappy@6.3.2 install /Users/oleg/Workspace/golang/src/github.com/CloudSpot/cloudspot/iu/node_modules/snappy
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=13.13.0 runtime=node arch=x64 libc= platform=darwin)
gyp: deps/snappy/common.gypi not found (cwd: /Users/oleg/Workspace/golang/src/github.com/CloudSpot/cloudspot/iu/node_modules/snappy) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/oleg/.fnm/node-versions/v13.13.0/installation/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/Users/oleg/.fnm/node-versions/v13.13.0/installation/bin/node" "/Users/oleg/.fnm/node-versions/v13.13.0/installation/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/oleg/Workspace/golang/src/github.com/CloudSpot/cloudspot/iu/node_modules/snappy
gyp ERR! node -v v13.13.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN cloudspot-api@6.5.4 No repository field.
npm WARN cloudspot-api@6.5.4 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snappy@6.3.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snappy@6.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/oleg/.npm/_logs/2020-04-21T19_59_13_223Z-debug.log
```

**Comment by oaleynik** [comment]
Also cannot be built on Nodejs v14

**Comment by kesla** [comment]
I couldn't get prebuilds to work with Node 14, but it should be possible to build from source now, I hope that works for you
