### ISSUE TITLE
failing snappy@6.3.3 node:11.15.0

### ISSUE THREAD

**Issue by whomobile** [kesla/node-snappy#190]
It looks v6.3.3 has some issues.

nodejs v11.15.0
base os CentOS

```
[root@912a2a6b2685 app]# npm install snappy@6.3.3
npm WARN deprecated fsevents@1.2.12: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> snappy@6.3.3 install /usr/src/app/node_modules/snappy
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.15.0 runtime=node arch=x64 libc= platform=linux)
make: Entering directory `/usr/src/app/node_modules/snappy/build'
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.7/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.7/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.7/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
  COPY Release/snappy.a
  SOLINK_MODULE(target) Release/obj.target/binding.node
g++: error: Release/obj.target/binding/src/binding.o: No such file or directory
make: *** [Release/obj.target/binding.node] Error 1
make: Leaving directory `/usr/src/app/node_modules/snappy/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 4.4.0-1104-aws
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app/node_modules/snappy
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok

```

**Comment by whomobile** [comment]
it works fine from ubutu base image.

**Comment by whomobile** [comment]
it works on ubuntu base image because it using prebuilt image. on centos it rebuild but binding.cc is missing.

**Comment by whomobile** [comment]
duplicate #189
