### ISSUE TITLE
Unable to install in node version 8.15.0 No prebuilt binaries found

### ISSUE THREAD

**Issue by vignesh-123** [kesla/node-snappy#192]
Tried npm install snappy 
It is throwing error saying

```
prebuild-install WARN install No prebuilt binaries found (target=8.15.0 runtime=node arch=x64 libc= platform=win32)
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Lenovo\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:281:12)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:336:11)
gyp ERR! stack     at emitOne (events.js:116:13)
gyp ERR! stack     at Socket.emit (events.js:211:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:561:12)
gyp ERR! System Windows_NT 10.0.18362
```

**Comment by vignesh-123** [comment]
The issue was with my local machine 
There was a python version mismatch
