### ISSUE TITLE
"invalid ELF header" in AWS Lambda

### ISSUE THREAD

**Issue by kdybicz** [kesla/node-snappy#201]
Hey,

I was trying to use Snappy to compress some data before pushing them to a datastore in my `Node 12.x` Lambda. Unfortunately I'm getting below error:

```
2021-03-14T13:39:14.674Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "/var/task/node_modules/snappy/build/Release/binding.node: invalid ELF header",
    "stack": [
        "Error: /var/task/node_modules/snappy/build/Release/binding.node: invalid ELF header",
        "    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Module.require (internal/modules/cjs/loader.js:887:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at bindings (/var/task/node_modules/bindings/bindings.js:112:48)",
        "    at Object.<anonymous> (/var/task/node_modules/snappy/snappy.js:2:34)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)"
    ]
}
```

Any ideas how I could solve that problem?

**Comment by kdybicz** [comment]
huh... I've solved it by googling a bit more. Turned out that the environment from which I'm running the deployment makes the difference. Lambda with Snappy is failing when deployed from macOS but it's working just fine when deployed from linux machine. I guess you can close that Issue, though I think it could make sense to write this down in some docs?

**Comment by kdybicz** [comment]
Though, I would still like to know how to deploy to linux Lambda nodes from macOS machine without such problems... any hints?

**Comment by kdybicz** [comment]
Found this workaround so far https://github.com/serverless/serverless/issues/308#issuecomment-685149964
