### ISSUE TITLE
npm install snappy fail

### ISSUE THREAD

**Issue by florentvaldelievre** [kesla/node-snappy#38]
Hi there,

I am not able to install snappy through npm, on Linux and windows 7. Not sure either why i need to set HOME env variable.

**Windows 7  ( Node v0.10.32)**
````

C:\dev\apps\todelete>npm install snappy
|
> snappy@3.0.6 install C:\dev\apps\todelete\node_modules\snappy
> node-gyp rebuild


C:\dev\apps\todelete\node_modules\snappy>node "C:\dev\tools\nodejs\node_modules\
npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:1001:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:792:
34)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\dev\\tools\\nodejs\\node_modules\\npm\\node_modules
\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dev\apps\todelete\node_modules\snappy
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! snappy@3.0.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snappy@3.0.6 install script.
npm ERR! This is most likely a problem with the snappy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls snappy
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\dev\\tools\\nodejs\\\\node.exe" "C:\\dev\\tools\\nodejs\\n
ode_modules\\npm\\bin\\npm-cli.js" "install" "snappy"
npm ERR! cwd C:\dev\apps\todelete
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
````

**Linux ( Node v0.10.32)**
````
[root@3a7b3919bcd1 tmp]# npm install snappy
-
> snappy@3.0.6 install /tmp/node_modules/snappy
> node-gyp rebuild


/usr/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:54
    throw new Error(
          ^
Error: node-gyp requires that the user's home directory is specified in either of the environmental variables HOME or USERPROFILE
    at new Gyp (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:54:11)
    at gyp (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/node-gyp.js:43:10)
    at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:20:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! snappy@3.0.6 install: `node-gyp rebuild`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the snappy@3.0.6 install script.
npm ERR! This is most likely a problem with the snappy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls snappy
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-504.1.3.el6.x86_64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "snappy"
npm ERR! cwd /tmp
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
````

**Comment by hex7c0** [comment]
on Linux env, print `echo $HOME`
because on travis (and my pc) builds normally
https://travis-ci.org/kesla/node-snappy/jobs/49365917#L91

**Comment by hex7c0** [comment]
Windows build
https://ci.appveyor.com/project/hex7c0/node-snappy/build/job/d7l1enttmy5w1wso

**Comment by florentvaldelievre** [comment]
Hi,

1) For linux, I don't have a $HOME variable set as I am working within a docker container. 
Could you please advise the reason why it needs $HOME variable ?
I managed to have snappy working by installing dev tool before npm install
````
yum install -y gcc-c++ make
npm install
````

2) For Windows, According to your logs on travis, it looks like it is using Microsoft Visual Studio 10.0 to compile some component. It seems to be a huge dependency for everyone using snappy. Is there a way to avoid it ?

Thanks

**Comment by hex7c0** [comment]
Hi,
snappy is a c++ project, so we need to compile it for nodejs using https://github.com/TooTallNate/node-gyp
and [these](https://github.com/TooTallNate/node-gyp#installation) are the requisites

about $HOME, `gyp` saves some libs inside `~/.node-gyp`

**Comment by florentvaldelievre** [comment]
Ok, thanks for your prompt reply !

**Comment by hex7c0** [comment]
you're welcome :)

**Comment by hex7c0** [comment]
@kesla what do you think about windows CI (like appveyor)?

**Comment by kesla** [comment]
@hex7c0 windows CI would be fantastic.
