### ISSUE TITLE
Can't build on Windows 7 x64

### ISSUE THREAD

**Issue by tobilg** [kesla/node-snappy#53]
I get the following error while trying to install on Win7 x64:
```
D:\Test>npm install snappy

> snappy@3.1.0 install D:\Test\node_modules\snappy
> node-gyp rebuild


D:\Test\node_modules\snappy>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(296,5): warning MSB8003: Could not find VCInstallDir variable from the registry.  TargetFrameworkVersi
on or PlatformToolset may be set to an invalid version number. [D:\Test\node_modules\snappy\build\deps\snappy\snappy.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(297,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.  TargetFrameworkVers
ion or PlatformToolset may be set to an invalid version number. [D:\Test\node_modules\snappy\build\deps\snappy\snappy.vcxproj]
  snappy-sinksource.cc
  snappy-stubs-internal.cc
  snappy.cc
..\..\..\deps\snappy\snappy-1.1.2\snappy-sinksource.cc(29): fatal error C1083: Cannot open include file: 'string.h': No such file or directory [D:\Test\
node_modules\snappy\build\deps\snappy\snappy.vcxproj]
..\..\..\deps\snappy\snappy-1.1.2\snappy-stubs-internal.cc(29): fatal error C1083: Cannot open include file: 'algorithm': No such file or directory [D:\Test\node_modules\snappy\build\deps\snappy\snappy.vcxproj]
d:\test\node_modules\snappy\deps\snappy\snappy-1.1.2\snappy.h(42): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory (.
.\..\..\deps\snappy\snappy-1.1.2\snappy.cc) [D:\Test\node_modules\snappy\build\deps\snappy\snappy.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Test\node_modules\snappy
gyp ERR! node -v v0.10.38
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! snappy@3.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snappy@3.1.0 install script.
npm ERR! This is most likely a problem with the snappy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls snappy
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "snappy"
npm ERR! cwd D:\Test\node_modules
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

Is there a way that I can install this onmy system? I have VisualStudio 2013 Express already installed.

**Comment by kesla** [comment]
Hey, I'm sorry about it not working for you.

I never use Windows and as such it's really hard for me to help out. Perhaps there's someone else who could help out?

**Comment by hex7c0** [comment]
hey tobilg,
mmm appveyor works https://ci.appveyor.com/project/kesla/node-snappy/build/job/enp98nispe59lvqj

have you seen this issue https://github.com/kesla/node-snappy/issues/38#issuecomment-73045881?

**Comment by tobilg** [comment]
Thanks for your comments. Yes, I already saw the issue #38, but I couldn't get it running. I think it's probably not a node-snappy problem, but more an overall node-gyp and Windows configuration problem. I installed VS 2013 Express as most people recommend (and removed any older version), but still I'm not able to get it to run. Thanks anyway for your help!
