### ISSUE TITLE
Node 4.0.0 Support

### ISSUE THREAD

**Issue by shinzui** [kesla/node-snappy#66]
Build currently fails on node 4.0.0. 

```
npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things
|
> snappy@4.0.0 install /private/tmp/node_modules/snappy
> pangyp rebuild

gyp: /Users/shinzui/.node-gyp/4.0.0/common.gypi not found (cwd: /private/tmp/node_modules/snappy) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/private/tmp/node_modules/snappy/node_modules/pangyp/lib/configure.js:346:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/shinzui/.nvm/versions/node/v4.0.0/bin/node" "/private/tmp/node_modules/snappy/node_modules/.bin/pangyp" "rebuild"
gyp ERR! cwd /private/tmp/node_modules/snappy
gyp ERR! node -v v4.0.0
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/shinzui/.nvm/versions/node/v4.0.0/bin/node" "/Users/shinzui/.nvm/versions/node/v4.0.0/bin/npm" "i" "https://github.com/kesla/node-snappy"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! snappy@4.0.0 install: `pangyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snappy@4.0.0 install script 'pangyp rebuild'.
npm ERR! This is most likely a problem with the snappy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     pangyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls snappy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/npm-debug.log
```

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by hefangshi** [comment]
I found that only made a tiny change in package.json will work fine with Node 4.0

```
{
  "author": "David Björklund <david.bjorklund@gmail.com>",
  "name": "snappy",
  "description": "Nodejs bindings to Google's Snappy compression library",
  "version": "4.0.0",
  "homepage": "https://github.com/kesla/node-snappy",
  "repository": {
    "type": "git",
    "url": "git://github.com/kesla/node-snappy.git"
  },
  "main": "snappy.js",
  "scripts": {
    "test": "tap test.js",
    "install": "node-gyp configure && node-gyp build"
  },
  "dependencies": {
    "bindings": "^1.2.0",
    "nan": "^2.0.0"
  },
  "devDependencies": {
    "tap": "^0.4.11"
  },
  "gypfile": true,
  "bugs": {
    "url": "https://github.com/kesla/node-snappy/issues"
  },
  "license": "MIT"
}
```

just change the `pangyp` to `node-gyp configure && node-gyp build`

**Comment by estliberitas** [comment]
So now, if I wanna use snappy, is not the right time to upgrade to 4.0.0?

**Comment by kkoopa** [comment]
Just patch package.json to use node-gyp instead of pangyp, or wait for the fix to be published.

**Comment by kesla** [comment]
@kkoopa I added a PR for this (https://github.com/kesla/node-snappy/pull/67) but it's failing in travis. The tests passes for me locally (node4 on Mac OS X) so I don't know if this is a real problem or if it's just travis?

**Comment by kkoopa** [comment]
You are not allowed to update npm for io.js or Node 4.

**Comment by estliberitas** [comment]
@kesla Btw, why do you run "npm install npm@2" in Travis? Just curious.

**Comment by kesla** [comment]
I finally got it working! So closing this :dancers: There's a snappy v4.0.1 with support & travis from node 0.8 to 4.0!

**Comment by estliberitas** [comment]
@kesla thanks!

**Comment by tb01923** [comment]
@kesla I am still having issues with this.  I have tried Node 4.0.0 and 4.1.0 and Snappy@4.0.1 once CentOS 6.5  There looks to be a ton of C++ bugs all associated with NAN.

**Comment by ChALkeR** [comment]
@tb01923 Minimum required gcc version is 4.8.

**Comment by tb01923** [comment]
@ChALkeR thank you.  I upgraded to 4.8.2 

    > sudo gcc --version
    gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
    Copyright (C) 2013 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

and think I have done this correctly, yet I am still unable to complile / install the underlying 4.0.1 library

```bash
sudo npm install snappy@4.0.1
-
> snappy@4.0.1 install /var/XYZ/node_modules/snappy
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.0.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/XYZ/node_modules/snappy/.node-gyp"
make: Entering directory `/var/XYZ/node_modules/snappy/build'
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy.o
/var/frt/node_modules/snappy/ccRiItQY.s: Assembler messages:
/var/frt/node_modules/snappy/ccRiItQY.s:487: Error: expecting string instruction after `rep'
make: *** [Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy.o] Error 1
make: Leaving directory `/var/XYZ/node_modules/snappy/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/nodejs-binary-4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-504.8.1.el6.x86_64
gyp ERR! command "/usr/local/nodejs-binary-4.0.0/bin/node" "/usr/local/nodejs-binary-4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/frt/node_modules/snappy
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm ERR! Linux 2.6.32-504.8.1.el6.x86_64
npm ERR! argv "/usr/local/nodejs-binary-4.0.0/bin/node" "/usr/local/bin/npm" "install" "snappy@4.0.1"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
```

**Comment by kesla** [comment]
@tb01923 can you install other compiled dependencies in centos?
