### ISSUE TITLE
CentOS 6.5 Node 4.1.0 via kafka-node (snappy@4.0.0)

### ISSUE THREAD

**Issue by tb01923** [kesla/node-snappy#69]
```bash

sudo npm install snappy@4.0.0
npm WARN deprecated pangyp@2.3.2: use node-gyp@3+, it does all the things
|
> snappy@4.0.0 install /var/some/node_modules/snappy
> pangyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.1.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/some/node_modules/snappy/.node-gyp"
make: Entering directory `/var/some/node_modules/snappy/build'
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.2/snappy.o
  AR(target) Release/obj.target/deps/snappy/snappy.a
  COPY Release/snappy.a
  CXX(target) Release/obj.target/binding/src/binding.o
In file included from /var/some/node_modules/snappy/.node-gyp/4.1.0/src/node.h:42,
                 from ../src/./binding.h:3,
                 from ../src/binding.cc:1:
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h:336: error: expected unqualified-id before ‘using’
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h:353: error: ‘nullptr’ was not declared in this scope
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h:360: error: ‘nullptr’ was not declared in this scope
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h:364: error: ‘nullptr’ was not declared in this scope
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h:430: error: ‘nullptr’ was not declared in this scope
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h: At global scope:
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h:469: error: expected unqualified-id before ‘using’
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h: In constructor ‘v8::Global<T>::Global()’:
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h:790: error: ‘nullptr’ was not declared in this scope
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h:815: error: ‘nullptr’ was not declared in this scope
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h:827: error: ‘nullptr’ was not declared in this scope
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h: At global scope:
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h:852: error: expected unqualified-id before ‘using’
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h:1089: error: ‘nullptr’ was not declared in this scope
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h:1095: error: ‘nullptr’ was not declared in this scope
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h:3205: error: ‘nullptr’ was not declared in this scope
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h:7151: error: ‘nullptr’ was not declared in this scope
In file included from ../node_modules/nan/nan.h:182,
                 from ../src/./binding.h:6,
                 from ../src/binding.cc:1:
../node_modules/nan/nan_maybe_43_inl.h: At global scope:
../node_modules/nan/nan_maybe_43_inl.h:13: error: expected unqualified-id before ‘using’
../node_modules/nan/nan_maybe_43_inl.h:16: error: expected unqualified-id before ‘using’
../node_modules/nan/nan_maybe_43_inl.h:19: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:24: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:31: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:36: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:41: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:46: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:51: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:60: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:65: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:70: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:77: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:84: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:92: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:99: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:109: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:115: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:119: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:126: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:131: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:136: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:140: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:146: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:151: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:157: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:163: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:169: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:175: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:181: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:187: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:195: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:202: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:206: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:210: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:214: error: expected initializer before ‘<’ token
../node_modules/nan/nan_maybe_43_inl.h:218: error: expected initializer before ‘<’ token
In file included from ../node_modules/nan/nan.h:187,
                 from ../src/./binding.h:6,
                 from ../src/binding.cc:1:
../node_modules/nan/nan_converters.h:14: error: ISO C++ forbids declaration of ‘MaybeLocal’ with no type
../node_modules/nan/nan_converters.h:14: error: expected ‘;’ before ‘<’ token
../node_modules/nan/nan_converters.h:16: error: ISO C++ forbids declaration of ‘Maybe’ with no type
../node_modules/nan/nan_converters.h:16: error: expected ‘;’ before ‘<’ token
../node_modules/nan/nan_converters.h:26: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:27: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:28: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:29: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:30: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:31: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:32: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:42: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:43: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:44: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:45: error: ‘return_t’ does not name a type
../node_modules/nan/nan_converters.h:46: error: ‘return_t’ does not name a type
In file included from ../node_modules/nan/nan_converters.h:59,
                 from ../node_modules/nan/nan.h:187,
                 from ../src/./binding.h:6,
                 from ../src/binding.cc:1:
../node_modules/nan/nan_converters_43_inl.h:18: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Boolean>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:19: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Number>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:20: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::String>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:21: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Object>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:22: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Integer>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:23: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Uint32>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:24: error: ‘return_t’ in class ‘Nan::imp::ToFactory<v8::Int32>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:34: error: ‘return_t’ in class ‘Nan::imp::ToFactory<bool>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:35: error: ‘return_t’ in class ‘Nan::imp::ToFactory<double>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:36: error: ‘return_t’ in class ‘Nan::imp::ToFactory<long int>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:37: error: ‘return_t’ in class ‘Nan::imp::ToFactory<unsigned int>’ does not name a type
../node_modules/nan/nan_converters_43_inl.h:38: error: ‘return_t’ in class ‘Nan::imp::ToFactory<int>’ does not name a type
In file included from ../node_modules/nan/nan.h:188,
                 from ../src/./binding.h:6,
                 from ../src/binding.cc:1:
../node_modules/nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Integer]’:
../node_modules/nan/nan_new.h:21: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../node_modules/nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Int32]’:
../node_modules/nan/nan_new.h:28: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../node_modules/nan/nan_new.h: In function ‘v8::Local<T> Nan::imp::To(v8::Local<v8::Integer>) [with T = v8::Uint32]’:
../node_modules/nan/nan_new.h:35: error: no matching function for call to ‘To(v8::Local<v8::Integer>&)’
../node_modules/nan/nan_new.h: At global scope:
../node_modules/nan/nan_new.h:43: error: ISO C++ forbids declaration of ‘MaybeLocal’ with no type
../node_modules/nan/nan_new.h:43: error: expected ‘;’ before ‘<’ token
../node_modules/nan/nan_new.h:75: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:141: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:147: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:148: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:160: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:161: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:162: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:163: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:165: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:166: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:182: error: ‘return_t’ does not name a type
../node_modules/nan/nan_new.h:183: error: ‘return_t’ does not name a type
In file included from ../node_modules/nan/nan_new.h:189,
                 from ../node_modules/nan/nan.h:188,
                 from ../src/./binding.h:6,
                 from ../src/binding.cc:1:
../node_modules/nan/nan_implementation_12_inl.h:56: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::Date>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static v8::Local<v8::Function> Nan::imp::Factory<v8::Function>::New(void (*)(const Nan::FunctionCallbackInfo<v8::Value>&), v8::Local<v8::Value>)’:
../node_modules/nan/nan_implementation_12_inl.h:90: error: ‘NewInstance’ was not declared in this scope
../node_modules/nan/nan_implementation_12_inl.h: In static member function ‘static v8::Local<v8::FunctionTemplate> Nan::imp::Factory<v8::FunctionTemplate>::New(void (*)(const Nan::FunctionCallbackInfo<v8::Value>&), v8::Local<v8::Value>, v8::Local<v8::Signature>)’:
../node_modules/nan/nan_implementation_12_inl.h:118: error: ‘NewInstance’ was not declared in this scope
../node_modules/nan/nan_implementation_12_inl.h: At global scope:
../node_modules/nan/nan_implementation_12_inl.h:197: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::RegExp>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:216: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::Script>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:222: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::Script>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:254: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:262: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:268: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:275: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:281: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:286: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:347: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::UnboundScript>’ does not name a type
../node_modules/nan/nan_implementation_12_inl.h:354: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::UnboundScript>’ does not name a type
In file included from ../node_modules/nan/nan.h:188,
                 from ../src/./binding.h:6,
                 from ../src/binding.cc:1:
../node_modules/nan/nan_new.h:291: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_new.h:297: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_new.h:303: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_new.h:309: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_new.h:315: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_new.h:321: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::String>’ does not name a type
../node_modules/nan/nan_new.h:327: error: ‘return_t’ in class ‘Nan::imp::Factory<v8::RegExp>’ does not name a type
In file included from ../src/./binding.h:6,
                 from ../src/binding.cc:1:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::Error(const char*)’:
../node_modules/nan/nan.h:639: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::ThrowError(const char*)’:
../node_modules/nan/nan.h:639: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::RangeError(const char*)’:
../node_modules/nan/nan.h:640: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::ThrowRangeError(const char*)’:
../node_modules/nan/nan.h:640: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::ReferenceError(const char*)’:
../node_modules/nan/nan.h:641: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::ThrowReferenceError(const char*)’:
../node_modules/nan/nan.h:641: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::SyntaxError(const char*)’:
../node_modules/nan/nan.h:642: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::ThrowSyntaxError(const char*)’:
../node_modules/nan/nan.h:642: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Value> Nan::TypeError(const char*)’:
../node_modules/nan/nan.h:643: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::ThrowTypeError(const char*)’:
../node_modules/nan/nan.h:643: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: At global scope:
../node_modules/nan/nan.h:651: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:673: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:689: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:702: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:719: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:725: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:733: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:740: error: expected initializer before ‘<’ token
../node_modules/nan/nan.h:746: error: expected initializer before ‘<’ token
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h: In member function ‘void Nan::Callback::SetFunction(const v8::Local<v8::Function>&)’:
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h:3021: error: argument dependent lookup finds ‘class v8::Set’
../node_modules/nan/nan.h:1366: error:   in call to ‘Set’
../node_modules/nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const char*, const v8::Local<v8::Value>&)’:
../node_modules/nan/nan.h:1488: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const char*) const’:
../node_modules/nan/nan.h:1506: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In member function ‘virtual void Nan::AsyncWorker::HandleErrorCallback()’:
../node_modules/nan/nan.h:1540: error: no matching function for call to ‘New(const char*)’
../node_modules/nan/nan.h: In function ‘void Nan::SetMethod(const T&, const char*, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&))’:
../node_modules/nan/nan.h:1829: error: there are no arguments to ‘GetFunction’ that depend on a template parameter, so a declaration of ‘GetFunction’ must be available
../node_modules/nan/nan.h:1829: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
../node_modules/nan/nan.h:1830: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::SetPrototypeMethod(v8::Local<v8::FunctionTemplate>, const char*, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&))’:
../node_modules/nan/nan.h:1842: error: ‘GetFunction’ was not declared in this scope
../node_modules/nan/nan.h:1843: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In function ‘void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, void (*)(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const Nan::PropertyCallbackInfo<void>&), v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, Nan::imp::Sig)’:
../node_modules/nan/nan.h:1868: error: ‘NewInstance’ was not declared in this scope
../node_modules/nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, void (*)(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const Nan::PropertyCallbackInfo<void>&), v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’:
../node_modules/nan/nan.h:1911: error: ‘NewInstance’ was not declared in this scope
../node_modules/nan/nan.h: In function ‘void Nan::SetNamedPropertyHandler(v8::Local<v8::ObjectTemplate>, void (*)(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const Nan::PropertyCallbackInfo<v8::Value>&), void (*)(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&), void (*)(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Boolean>&), void (*)(const Nan::PropertyCallbackInfo<v8::Array>&), v8::Local<v8::Value>)’:
../node_modules/nan/nan.h:1959: error: ‘NewInstance’ was not declared in this scope
../node_modules/nan/nan.h: In function ‘void Nan::SetIndexedPropertyHandler(v8::Local<v8::ObjectTemplate>, void (*)(uint32_t, const Nan::PropertyCallbackInfo<v8::Value>&), void (*)(uint32_t, v8::Local<v8::Value>, const Nan::PropertyCallbackInfo<v8::Value>&), void (*)(uint32_t, const Nan::PropertyCallbackInfo<v8::Integer>&), void (*)(uint32_t, const Nan::PropertyCallbackInfo<v8::Boolean>&), void (*)(const Nan::PropertyCallbackInfo<v8::Array>&), v8::Local<v8::Value>)’:
../node_modules/nan/nan.h:2029: error: ‘NewInstance’ was not declared in this scope
In file included from ../src/./binding.h:6,
                 from ../src/binding.cc:1:
../node_modules/nan/nan.h: In function ‘void Nan::Export(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE, const char*, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&))’:
../node_modules/nan/nan.h:2090: error: no matching function for call to ‘New(const char*&)’
../node_modules/nan/nan.h:2091: error: ‘GetFunction’ was not declared in this scope
/var/some/node_modules/snappy/.node-gyp/4.1.0/deps/v8/include/v8.h:3021: error: argument dependent lookup finds ‘class v8::Set’
../node_modules/nan/nan.h:2091: error:   in call to ‘Set’
../node_modules/nan/nan.h: In constructor ‘Nan::Tap::Tap(v8::Local<v8::Value>)’:
../node_modules/nan/nan.h:2098: error: no matching function for call to ‘To(v8::Local<v8::Value>&)’
../node_modules/nan/nan.h: In member function ‘void Nan::Tap::ok(bool, const char*)’:
../node_modules/nan/nan.h:2111: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../node_modules/nan/nan.h: In member function ‘void Nan::Tap::pass(const char*)’:
../node_modules/nan/nan.h:2117: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../src/binding.cc: In member function ‘virtual void nodesnappy::CompressWorker::HandleOKCallback()’:
../src/binding.cc:29: error: ‘NewBuffer’ is not a member of ‘Nan’
../src/binding.cc: In member function ‘virtual void nodesnappy::UncompressWorker::HandleOKCallback()’:
../src/binding.cc:92: error: ‘NewBuffer’ is not a member of ‘Nan’
../src/binding.cc:95: error: no matching function for call to ‘New(const char*, size_t)’
../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE nodesnappy::CompressSync(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/binding.cc:154: error: ‘NewBuffer’ is not a member of ‘Nan’
../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE nodesnappy::Uncompress(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/binding.cc:199: error: ‘Get’ is not a member of ‘Nan’
../src/binding.cc:199: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE nodesnappy::UncompressSync(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../src/binding.cc:224: error: ‘Get’ is not a member of ‘Nan’
../src/binding.cc:224: error: ‘class v8::Local<v8::Boolean>’ has no member named ‘ToLocalChecked’
../src/binding.cc:233: error: ‘NewBuffer’ is not a member of ‘Nan’
../src/binding.cc:236: error: no matching function for call to ‘New(const char*, size_t)’
In file included from ../src/./binding.h:6,
                 from ../src/binding.cc:1:
../node_modules/nan/nan.h: In function ‘void Nan::SetMethod(const T&, const char*, void (*)(const Nan::FunctionCallbackInfo<v8::Value>&)) [with T = Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE]’:
../src/binding.cc:244:   instantiated from here
../node_modules/nan/nan.h:1829: error: ‘GetFunction’ was not declared in this scope
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory `/var/some/node_modules/snappy/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/var/some/node_modules/snappy/node_modules/pangyp/lib/build.js:272:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-504.8.1.el6.x86_64
gyp ERR! command "/usr/local/nodejs-binary-4.1.0/bin/node" "/var/some/node_modules/snappy/node_modules/.bin/pangyp" "rebuild"
gyp ERR! cwd /var/some/node_modules/snappy
gyp ERR! node -v v4.1.0
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok 
npm ERR! Linux 2.6.32-504.8.1.el6.x86_64
npm ERR! argv "/usr/local/nodejs-binary-4.1.0/bin/node" "/usr/local/bin/npm" "install" "snappy@4.0.0"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! snappy@4.0.0 install: `pangyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snappy@4.0.0 install script 'pangyp rebuild'.
npm ERR! This is most likely a problem with the snappy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     pangyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls snappy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/some/npm-debug.log
```

**Comment by tb01923** [comment]
Duplicate
